### PR TITLE
Add write function for Meadowlark SLM

### PR DESCRIPTION
**Pull request by JulesScholler**

### CODE REVIEW

**Comment by brandondube** [comment]
Thanks for the PR!  Some comments:

- You can use is_odd from `prysm.util`, if you need to test if something is even you can just use `!is_odd` for integers.  I think in your code it is odd or not not odd -- otherwise some 'pixels' will be dropped.

- Please use a context manager, `with open(file, 'w') as fid:` and write your code inside that block.  An error between L1098 and L1105 would result in a leaked file descriptor, [something we don't want to do!](https://martin-ueding.de/articles/c-file-descriptors/index.html)

- What are the magic values in the two header lines?

- What is the magic number 12?  Perhaps it can become a function argument `Rmax`?

- A double for loop will be very slow for large arrays.  Your code looks fairly vectorizable - it looks like it is just a header than tab separated lines of x, y, z?  I found [a manual](https://www.meadowlark.com/store/SLM_manual_1.04.pdf) which has a file spec for a hexagonal array.    Going by this manual, I made a more flexible and vectorized writer - https://gist.github.com/brandondube/85dd60e89c144ecd6cfc46f6bc5d1e38 . It can write video sequences!  Note this assumes x, y are integer pixel indices starting at 1.

If you want to make the requested changes to your version, or tweak my version and make a unit test (even if it only covers basic functionality) I'll accept the PR.

**Comment by JulesScholler** [comment]
Thanks for the feedback:

- I did not know that prysm already included `is_odd`, I'll modify it.
- I wasn't aware of this context manager trick, this is very interesting.
- The number of pixel is 128 (that's the only available version), therefore the maximum diameter is 12 in order to get the correct pixel coordinates.
- I know that it looks ugly but it will result in approx 200 loops in total so I was not very worried.

I'll run and test your vectorized version and PR it.

**Comment by brandondube** [comment]
Was your version converting from mm to px internally?  This wasn't clear -- the concept I made just assigns pixel coordinates and doesn't have real spatial units.

The context manager trick is something you should always use when working with files -- it's a best practice for python.

In the version I wrote, you can actually do away with the StringIO and read/write - that will actually be faster, just write directly to `fid` after writing the header.

**Comment by brandondube** [comment]
👋 have you had a chance to look at this?  I'd love to get it merged!

**Comment by JulesScholler** [comment]
👋 Your vectorized version is not working. The way the pixels are assigned is very confusing for this SLM, so you have to use a double for loop reasonning on parity (there is a total of 325 iterations so no big arrays) or to write down all the coordinates. 

I can send you a PR with the updated header line and use a context manger and include the multi-frame capability (even if it is not going to be useful to anyone who wants to trigger the SLM with an external signal).

**Comment by brandondube** [comment]
Ok - we just have to map rectangular coordinates to hexagonal ones.  Do we want the user to be required to resize their data to an appropriate number of pixels a priori, or make this function do resizing internally, perhaps 'magically' to accommodate larger data?

A [manual](https://www.meadowlark.com/store/SLM_manual_1.04.pdf) shows their indexing scheme.  It looks like it's just zero centered pseudo-cartesian coordinates.  From [here](https://www.redblobgames.com/grids/hexagons/) we can make a vectorized function to map the cartesian/pixel coordinates to hex coordinates, then round them to nearest hexagonal pixel and average.  The cartesian to hex function would belong in prysm.coordinates.

**Comment by brandondube** [comment]
close - triage/abandoned

**Pull request closed without merging**
