### PR TITLE
Update io.py

### PR DESCRIPTION
**Pull request by erik-bu**
Adding unit support for height/phase unit of 'NanoMeters'. This is one of the unit options for Zygo data export.

### CODE REVIEW

**Comment by brandondube** [comment]
Thanks for the PR!  Could you provide a sample datx file showing that it works?  I understand IP ownership problems with that.  If not, can you just show a file in HDF5Viewer highlighting the attribute?  This is a really trivial addition but I still want to dot the is and cross the ts.

**Comment by erik-bu** [comment]
I am happy to contribute, even if it is just a tiny addition. I can't share a file, due to IP reasons.  I've attached a screen cap of the unit output from h5py. I think that should suffice.  Let me know if you need anything else.  Thanks!

NanoMeters_screencap

**Comment by brandondube** [comment]
yes, that'll do.  I made the merge, cheers!

**Comment by brandondube** [comment]
As a followup, this is now in a stable release, v0.19.1 -- see [release notes](https://prysm.readthedocs.io/en/stable/releases/v0.19.1.html)

Happy Holidays!

**Pull request merged**
